services:
  - type: web
    name: mafia-socket-server
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: CLIENT_ORIGIN
        value: https://mafia-f2r5.onrender.com
