services:
  - type: web
    name: mafia-socket-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    healthCheckPath: /health
    envVars:
      - key: CLIENT_ORIGIN
        sync: false
